### model
model_name_or_path: zhenting/myllama-4B-160BT-cpt-MixedFW8FM42

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /path/to/llama-factory/config_hub/official_configs/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: sampled500k_first100k_qwen7b
template: default
cutoff_len: 2048
max_samples: 1000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /path/to/llamafactory_out/myllama-4B-160BT-cpt-MixedFW8FM42-sftep1-sampled500k_first100k_qwen7b
logging_steps: 10
save_steps: 1000
plot_loss: false
overwrite_output_dir: true

### train
# 4 * 32 * 1 GPU = 128 | 4 * 16 * 2 GPU = 128 | 4 * 8 * 4 GPU = 128 | 4 * 4 * 8 GPU = 128
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 7.5e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
do_eval: false

### wandb
report_to: wandb
run_name: myllama-4B-160BT-cpt-MixedFW8FM42-sftep1-sampled500k_first100k_qwen7b

